# Workflow de CI para rodar linters, testes e verificação de qualidade de código
name: Integracao Continua

on: [push, workflow_dispatch]

jobs:
  test:
    name: Test on ${{ matrix.os }} with Python
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]
        python-version:
          - "3.x"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Instala a versão do Python definida na matriz
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # Cache das dependências do PDM
      - name: Cache PDM dependencies for Python ${{ matrix.python-version }}
        uses: actions/cache@v4
        with:
          path: |
            __pypackages__/
            .venv/
          key: ${{ runner.os }}-pdm-python-${{ matrix.python-version }}-${{ hashFiles('**/pdm.lock') }}
          restore-keys: |
            ${{ runner.os }}-pdm-python-${{ matrix.python-version }}-

      # Instala o PDM, dependências do projeto e checa integridade dos pacotes
      - name: Install Python ${{ matrix.python-version }} dependencies for ${{ matrix.os }}
        run: |
          python -m pip install --upgrade pip
          pip install pdm
          pdm install --dev
          pdm run pip check
        shell: bash

      # Roda o linter "ruff"
      - name: Rodar ruff
        run: pdm run ruff check src/

      # Roda os testes do Pytest gerando o relatório de cobertura XML
      - name: Run Tests with Coverage
        run: pdm run pytest --cov=. --cov-report=xml
        shell: bash

      # Envia os resultados dos testes e cobertura para o SonarCloud usando suas chaves reais
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=crypto_engsoft2
            -Dsonar.organization=engsoft2
            -Dsonar.python.coverage.reportPaths=coverage.xml
